# -*- coding: utf-8 -*-
"""Kelompok3_TugasKelompokM5_RC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PHd9F7N-CECJwbz8ORKAPEMW5yzFoHh
"""

import functools

def jadwal():
    courses = {}

    def decorator(func):
        @functools.wraps(func)
        def wrapper(course_info):
            nonlocal courses
            course_name, hari, jam_mulai, jam_selesai = course_info
            schedule = f"{hari} {jam_mulai}-{jam_selesai}"
            courses[course_name] = schedule
            print(f"{course_name} berhasil ditambahkan ke jadwal studi.")

            # Simpan jadwal ke dalam file
            with open("jadwal.txt", "a") as file:
                file.write(f"{course_name},{hari},{jam_mulai},{jam_selesai}\n")

        return wrapper
    return courses, decorator

def load_schedule():
    courses = {}
    try:
        with open("jadwal.txt", "r") as file:
            for line in file:
                course_info = line.strip().split(",")
                course_name = course_info[0]
                hari, jam_mulai, jam_selesai = course_info[1:]
                schedule = f"{hari} {jam_mulai}-{jam_selesai}"
                courses[course_name] = schedule
    except FileNotFoundError:
        pass  # If the file doesn't exist, no need to do anything

    return courses

courses, add_course = jadwal()
courses.update(load_schedule())

def remove_course(course_name):
    if course_name in courses:
        del courses[course_name]
        print(f"{course_name} berhasil dihapus dari jadwal studi.")

        # Save the updated schedule back to the file
        with open("jadwal.txt", "w") as file:
            for course, schedule in courses.items():
                hari, jam = schedule.split(" ")
                jam_mulai, jam_selesai = jam.split("-")
                file.write(f"{course},{hari},{jam_mulai},{jam_selesai}\n")

    else:
        print(f"Tidak ada {course_name} dalam jadwal studi.")

def change_schedule(course_name, new_schedule):
    if course_name in courses:
        courses[course_name] = new_schedule
        print(f"Jadwal {course_name} berhasil diubah.")

        # Save the updated schedule back to the file
        with open("jadwal.txt", "w") as file:
            for course, schedule in courses.items():
                hari, jam = schedule.split(" ")
                jam_mulai, jam_selesai = jam.split("-")
                file.write(f"{course},{hari},{jam_mulai},{jam_selesai}\n")

    else:
        print(f"Tidak ada {course_name} dalam jadwal studi.")

def display_schedule():
    print("Jadwal Studi:")
    if not courses:
        print("Tidak ada mata kuliah dalam jadwal studi.")
    else:
        for course, schedule in courses.items():
            print(f"{course}: {schedule}")

# Function to add a new course
def add_new_course():
    course_name = input("Masukkan nama kursus: ")
    hari = input("Masukkan hari jadwal (contoh: Senin): ")
    jam_mulai = input("Masukkan jam mulai (format: HH:MM, contoh: 08:00): ")
    jam_selesai = input("Masukkan jam selesai (format: HH:MM, contoh: 10:00): ")

    schedule = (course_name, hari, jam_mulai, jam_selesai)
    add_course(schedule)

# Function to remove a course
def remove_existing_course():
    course_name = input("Masukkan nama kursus yang akan dihapus: ")
    remove_course(course_name)

# Function to change the schedule of a course
def change_existing_schedule():
    course_name = input("Masukkan nama kursus yang jadwalnya akan diubah: ")
    hari = input("Masukkan hari baru (contoh: Senin): ")
    jam_mulai = input("Masukkan jam mulai baru (format: HH:MM, contoh: 08:00): ")
    jam_selesai = input("Masukkan jam selesai baru (format: HH:MM, contoh: 10:00): ")
    new_schedule = f"{hari} {jam_mulai}-{jam_selesai}"
    change_schedule(course_name, new_schedule)

# Function to display the menu
def display_menu():
    print("\nMenu:")
    print("1. Tambahkan Kursus Baru")
    print("2. Hapus Kursus")
    print("3. Ubah Jadwal Kursus")
    print("4. Tampilkan Jadwal Studi")
    print("5. Keluar")

# Program Usage
while True:
    display_menu()
    choice = input("Pilih menu: ")

    if choice == "1":
        add_new_course()
    elif choice == "2":
        remove_existing_course()
    elif choice == "3":
        change_existing_schedule()
    elif choice == "4":
        display_schedule()
    elif choice == "5":
        print("Terima kasih telah menggunakan program.")
        break
    else:
        print("Menu tidak valid. Silakan pilih kembali.")

